import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { HiOutlineQrCode, HiOutlinePrinter, HiOutlineMagnifyingGlass, HiOutlinePlusCircle } from 'react-icons/hi2';
import useFetch from '../../hooks/useFetch';
import DataTable from '../../components/DataTable';
import PageHeader from '../../components/PageHeader';
import { getDashboardStats, getBarcodeLogs } from '../../services/barcode.service';

const BarcodeDashboard = () => {
  const navigate = useNavigate();
  const [stats, setStats] = useState(null);

  const { data, pagination, loading, setPage, setSearch } = useFetch(getBarcodeLogs);

  useEffect(() => {
    getDashboardStats()
      .then((res) => setStats(res.data.data))
      .catch(() => {});
  }, []);

  const statCards = [
    { label: 'Total Products', value: stats?.totalProducts || 0, color: 'bg-blue-50 text-blue-700' },
    { label: 'With Barcode', value: stats?.withBarcode || 0, color: 'bg-green-50 text-green-700' },
    { label: 'Without Barcode', value: stats?.withoutBarcode || 0, color: 'bg-yellow-50 text-yellow-700' },
    { label: 'Total Generated', value: stats?.totalGenerated || 0, color: 'bg-purple-50 text-purple-700' },
  ];

  const quickActions = [
    { label: 'Generate Barcodes', icon: HiOutlinePlusCircle, path: '/barcodes/generate', color: 'bg-blue-600' },
    { label: 'Print Labels', icon: HiOutlinePrinter, path: '/barcodes/print', color: 'bg-green-600' },
    { label: 'Scanner', icon: HiOutlineMagnifyingGlass, path: '/barcodes/scan', color: 'bg-purple-600' },
  ];

  const columns = [
    { key: 'barcode', label: 'Barcode', render: (row) => <span className="font-mono text-sm">{row.barcode}</span> },
    { key: 'product', label: 'Product', render: (row) => row.product?.name || '-' },
    { key: 'barcodeType', label: 'Type' },
    { key: 'type', label: 'Method', render: (row) => <span className="capitalize">{row.type}</span> },
    { key: 'printCount', label: 'Printed', render: (row) => row.printCount || 0 },
    { key: 'generatedBy', label: 'Generated By', render: (row) => row.generatedBy?.name || '-' },
    {
      key: 'createdAt',
      label: 'Date',
      render: (row) => new Date(row.createdAt).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }),
    },
  ];

  return (
    <div>
      <PageHeader title="Barcode Management" subtitle="Generate, assign, and print barcodes">
        <HiOutlineQrCode className="w-6 h-6 text-gray-400" />
      </PageHeader>

      {/* Stats */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
        {statCards.map((card) => (
          <div key={card.label} className={`rounded-xl p-4 ${card.color}`}>
            <p className="text-sm opacity-80">{card.label}</p>
            <p className="text-2xl font-bold">{card.value}</p>
          </div>
        ))}
      </div>

      {/* Quick Actions */}
      <div className="flex items-center gap-3 mb-6">
        {quickActions.map((action) => (
          <button
            key={action.label}
            onClick={() => navigate(action.path)}
            className={`flex items-center gap-2 px-4 py-2.5 text-sm font-medium text-white rounded-lg hover:opacity-90 ${action.color}`}
          >
            <action.icon className="w-4 h-4" />
            {action.label}
          </button>
        ))}
      </div>

      {/* Recent Barcodes */}
      <h3 className="text-sm font-semibold text-gray-700 mb-3">Recent Barcode Activity</h3>
      <DataTable
        columns={columns}
        data={data || []}
        pagination={pagination}
        onPageChange={setPage}
        onSearch={setSearch}
        loading={loading}
      />
    </div>
  );
};

export default BarcodeDashboard;
